# Create a docker container using Jenkins image and using a volume for persistence

version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins_first_project
    privileged: true
    user: root
    volumes:
      - $PWD/first_devops_project/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: